version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bedrock-cfn-stacksetroles"
region = "ap-southeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
