name: Terraform Managment Deployment
on:
  push:
    branches:
      - main
    paths:
      - tf/management/**
  pull_request:
    paths:
      - tf/management/**
  workflow_dispatch:

jobs:
# Ensure the Organisation has all the required outputs for the Accounts
  call-org:
    uses: ./.github/workflows/tf-account.yml
    with:
      account: org
    secrets:
      AWS_ROOT_ACCOUNT: ${{ secrets.AWS_ROOT_ACCOUNT }}
      BEDROCK_TF_VARS: ${{ secrets.BEDROCK_TF_VARS }}
      BEDROCK_TF_STATE: ${{ secrets.BEDROCK_TF_STATE }}

# Managment Account Baseline
  call-managment:
    needs: call-org
    uses: ./.github/workflows/tf-account.yml
    with:
      account: managment
    secrets:
      AWS_ROOT_ACCOUNT: ${{ secrets.AWS_ROOT_ACCOUNT }}
      BEDROCK_TF_VARS: ${{ secrets.BEDROCK_TF_VARS }}
      BEDROCK_TF_STATE: ${{ secrets.BEDROCK_TF_STATE }}
